[server]
pattern = "DEV"

[database.shared_db]
type = "postgresql"
hostname = "postgre.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[database.identity_db]
type = "postgresql"
hostname = "postgresql.example.com"
database = "wso2isdb"
password = "$secret{db_password}"

[secrets]
db_password = "encrypted_value_2"
